version: "3"

services:
  apollo-web-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/developer/develop/node_modules
      - ..:/home/developer/develop
      - ${HOME}/.ssh:/home/developer/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - USER=developer
      - UID
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=demo
  postgres:
    container_name: postgres-sql
    hostname: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
